import React from 'react'

function Exprience() {
  return (
    <div className='p-5'>
      <p>this is hte exprience page where data from the database show the exprience in that city where you want to go to visit or travel to that city. Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus in omnis neque itaque, fugiat accusantium quaerat odio eos nesciunt, animi alias amet at nulla porro fugit molestiae! Praesentium molestias similique optio consequuntur veritatis, doloremque sunt aperiam! Id consequuntur quaerat ducimus in esse quam necessitatibus deleniti eligendi commodi repellat vero ex nemo quod, quis laborum itaque repellendus quasi voluptates cum impedit. Error debitis iusto culpa, laudantium voluptatum tempore, autem, dolorum ipsum et ipsa a expedita libero doloribus iure veniam deleniti delectus optio! Earum tempore autem ipsum, aliquam consequatur quis maxime nam, dolore praesentium impedit quam esse quas laudantium obcaecati atque repellendus perspiciatis. Eaque, doloremque ab? Tenetur quaerat, qui ut placeat distinctio officia eum aliquam explicabo. Voluptas corporis non quo ea quos nesciunt deserunt maxime error cum dolorum quibusdam quasi amet, suscipit molestiae excepturi vitae ad? Obcaecati repudiandae placeat tempora, modi unde vel doloremque ratione. Nam tempore nemo, nostrum maxime atque cupiditate minima doloribus dolor ducimus sed, eos optio excepturi, corrupti nisi debitis. Ipsa consequatur autem adipisci dolorum commodi voluptates error recusandae sed exercitationem minima suscipit consequuntur repudiandae laboriosam ad doloribus sit nemo, dignissimos tempora magnam cumque veritatis et officiis. Maiores commodi velit nam possimus doloremque quisquam fugit veniam saepe, quibusdam dolor! Nemo, esse iure labore accusantium ratione iusto quia voluptates cum eveniet iste ad placeat maiores? Possimus repudiandae molestias iusto sequi excepturi porro ipsam sed asperiores temporibus rerum accusantium numquam quae vero eaque ut, totam beatae expedita dolorum facere harum quasi at, vitae perspiciatis! Molestiae officiis reiciendis itaque quae repudiandae magnam consequatur adipisci magni, impedit, possimus exercitationem. Tempore non, quisquam iusto ab, quia quae consequuntur sit ad sequi id nobis pariatur repellendus deserunt odio fuga repudiandae optio natus est laborum aliquid eaque omnis tenetur, accusantium provident. Est saepe in, amet repellendus fuga officiis ut iure cumque illum ex, ad maxime sunt!</p>
    </div>
  )
}

export default Exprience
