import React from 'react'

function Services() {
  return (
    <div className='p-5'>
      <p>this is the services page Lorem ipsum dolor, sit amet consectetur adipisicing elit. Blanditiis consequatur illum et molestiae amet omnis, fugit ab natus odio doloremque eos architecto cum? Nihil quam enim ad accusantium asperiores dolores dolorem explicabo ipsum aperiam cupiditate obcaecati iste temporibus reprehenderit earum similique non alias, vel sint delectus excepturi minima reiciendis commodi praesentium. Debitis, qui. Adipisci rerum dicta qui dolor accusantium accusamus, ut tempore nihil corporis. Veniam sunt nulla error recusandae mollitia, placeat eum. Recusandae fugit impedit ex obcaecati eos tempora. Enim est animi nam, dolore fugiat magnam dolorem, ipsa, placeat ab laudantium earum. Suscipit deserunt commodi temporibus nobis soluta libero praesentium, corrupti debitis minus porro eaque. Unde tempore minus autem, quis assumenda necessitatibus itaque voluptas. Maxime consequuntur eligendi dignissimos porro hic qui temporibus ab eveniet, aut beatae vero iure voluptate mollitia natus similique officiis incidunt libero quis. Pariatur laudantium eos dignissimos harum unde nostrum hic, nam quaerat cum modi ad odit fuga enim illum, ab atque sed ducimus alias labore doloremque voluptate non. Fuga nihil aliquam voluptates neque vel vero, fugiat voluptatum consequatur ex non voluptatibus magni, eligendi labore beatae odio quas nostrum eveniet sunt perferendis! Vitae ipsum eligendi adipisci natus excepturi fugit cum velit repellendus a nemo! Autem quis nam accusamus iusto dolor voluptatem qui vero, illum quaerat ex architecto. Quos culpa adipisci nemo natus necessitatibus dicta iste velit sit maiores quisquam doloremque nulla, nesciunt dignissimos, pariatur sunt at! Ratione fugiat quae optio fugit quaerat dolores. Obcaecati nemo, ad quaerat quidem tempora corrupti labore iusto praesentium eum nostrum eligendi dolore quam incidunt quas eos, ut explicabo adipisci cupiditate! Consequatur nisi architecto expedita voluptatum, est ipsa velit dolores natus tempore dicta quasi? Necessitatibus repellendus incidunt exercitationem recusandae dolores qui natus omnis aperiam inventore enim unde alias, dolore illum doloremque non corporis est blanditiis eum officia porro esse at officiis ex. Aliquam!</p>
    </div>
  )
}

export default Services
